### ISSUE TITLE
why "import millify" (I notice you don't use it) ?

### ISSUE THREAD

**Issue by faustogut** [rodrigoprieto/crypto_panel#4]
Hi.
Yesterday I added millify to requirements.txt so I can build and run the app and it worked.
However, today I've noticed that there is not use of millify in your code, so you can remove the import sentence and the requirements line, unless you plan to use it.
Why did you do? Following YAGNI principle, you must remove it.

**Comment by rodrigoprieto** [comment]
I'm planning to use it since it's a good way to show big numbers when we print Open interest or Volume using reduced format.
For example instead to see 452655532 it will read 452 M which looks better to visualize.
This project is work & progress. I very appreciate all your editions and comments.
